### ISSUE TITLE
Arkaplanda istenmeyen çalma

### ISSUE THREAD

**Issue by kemalsanli** [KebabLord/turkanime-indirici#11]
Merhabalar,

Programın son commitinde indirme başlattığımda sanıyorum ki linkleri bulmak için videoyu arka planda açıyor arka planda kapatılamayan bir video oynamaya başlıyor ve hiç bir şekilde durdurulamıyor.

```
Videonun aktif olduğu doğrulandı...                   
[generic] redirector?token=*************: Requesting header
[redirect] Following redirect to https://www48.ff-01.com/token=*************c31ff-480p.mp4
[generic] *************31ff-480p: Requesting header
[download] Destination: /Users/Downloads/shingeki_no_kyojin/shingeki_no_kyojin_4_bolum.mp4

```

Emin değilim ama sanırım fembed'den kaynaklanıyor olabilir.

**Comment by kemalsanli** [comment]
Bu sorun güncel olmayan bir sürüm ile alakalıymış bu yüzden yeni sürümde testleri yapana kadar bu issue'yu kapatıyorum, rahatsızlık için ise üzgünüm.

**Comment by KebabLord** [comment]
o7
