### ISSUE TITLE
Youtube.dl hatası

### ISSUE THREAD

**Issue by YAKlNDA** [KebabLord/turkanime-indirici#12]
Böyle bir hata alıyorum yardımcı olabilirmisin ?_ 
https://prnt.sc/y6u18s

**Comment by gokaybiz** [comment]
En guncel mpv surumuyle tekrar deneyebilir misin?

**Comment by KebabLord** [comment]
Anladığım kadarıyla yaşadığın sıkıntı One Piece'in 500.bölümünü oynatmaya çalıştığında gerçekleşiyor. Windows7'de gömülü mpv ve youtube-dl sürümleriyle kendim test ettiğimde hiçbir sıkıntı olmadığını gözlemledim. Firewall'un yada antivirüs'ün uygulamayı engellemediğinden emin misin? Uygulamayı ilk açışında izin ver/reddet sorgusu geldiğinde onayladın mı? Kaynak kodundan mı çalıştırıyorsun yoksa derlenmiş .exe versiyonda mı bu sorunu yaşıyorsun?

**Comment by YAKlNDA** [comment]
turkanime.py den çalıstırıyorum 
indirme kısmında sıkıntı  yok 
firewall'ı devre dılı bıraktım ama gene alıyorum hatayı

**Comment by KebabLord** [comment]
o zaman sorun kesinlikle sisteminde kurulu mpv'den kaynaklanıyor. Windows'ta isen mpv'nin dizininde bulunan güncelleme scriptini çalıştırabilir ya da güncel bir release indirebilirsin.

**Comment by YAKlNDA** [comment]
Şuanda mpv'nin son sürümünü yükledim şuanda hatayı vermiyor onun yerine hiç bir şey olmuyor 
![unknown](https://user-images.githubusercontent.com/66492207/106910909-bb0a0380-6712-11eb-8007-1be9cd1a55d1.png)

**Comment by KebabLord** [comment]
gittikçe ilginçleşiyor. Mpv'nin windows sürümü cmd'de video oynatılırken hiçbir output vermiyor yazı çıkmaması doğal ama video'nun gelmemesi garip. 10-20 saniyelik beklemeye rağmen video gelmiyorsa debuglama vakti gelmiştir.
şu komutu çalıştırıp `mpv --referrer=https://video.sibnet.ru/ https://video.sibnet.ru/shell.php?videoid=2650474 --log-file log.txt` bu komudu çalıştırdığın klasörde oluşan log.txt'yi buraya atar mısın? Bu arada işletim sistemin nedir?
Ayrıyetten son ![release](https://github.com/KebabLord/turkanime-indirici/releases/download/v5.3.1/TurkAnimu.exe)'i indirip denediğinde sorun çıkartıyor mu? Son release kendi içinde gömülü bir mpv kullanıyor sistemindeki yerine.

**Comment by YAKlNDA** [comment]
Çok Teşekkürler Sorunu çözdüm 
Biz bir yolunu bulduk Hallettik 
bu arada uygulama mükemmel olmuş Ellerine sağlık ♥

**Comment by YAKlNDA** [comment]
Turkanimu'yu denemedim hiç pyhton felan kullanmayı hiç bilmiyorum zaten ama yinede bu hatayı veriyor Nasıl kurulucağını bilemedim 
![Screenshot_1](https://user-images.githubusercontent.com/66492207/106917194-13440400-6719-11eb-8775-460f812c27c6.png)

**Comment by KebabLord** [comment]
oradaki hatanın çözümü bu, sıradaki sürümde giderilecek
https://github.com/KebabLord/turkanime-indirici/wiki/hata:-Failed-to-execute-script-Turkanime

>  Biz bir yolunu bulduk Hallettik

merak ettim doğrusu

> bu arada uygulama mükemmel olmuş Ellerine sağlık

çok teşekkürler :3
