### ISSUE TITLE
İndirilen dosyalarda altyazı olmaması 

### ISSUE THREAD

**Issue by kemalsanli** [KebabLord/turkanime-indirici#13]
Merhabalar, herhangi bir sorun olmadan kullanmaktaydım fakat bu gün indirdiğim bir animede gömülü altyazı olmadığını farkettim. Dosya isimleri URL’den geldiği için altyazı dosyalarını da bulamadım. 

Harici altyazı içeren siteleri engellemenin bir yolu olsa güzel olabilirdi, veya altyazıları da aynı klasöre indirebilseydik bu sorunun üstesinden gelebilirdik. Eğer bu sorunu çözebilirseniz çok sevinirim, kolay gelsin.

Güncelleme:
Bulduğum geçici ve yavaş çözüm:

turkanime_api>players.py içerisinde şu değişikliği yaptım.

```
desteklenen_players = [
    #"SIBNET",
    "VK",
    "GPLUS",
    "GDRIVE",
    "YANDISK",
    "VIDMOLY",
    "DAILYMOTION",
    "MAIL",
    "MYVI",
    "ODNOKLASSNIKI",
    "SENDVID",
    "YOURUPLOAD"
]
```
AoT 1.Sezon 14.Bölümde deneme yapabilirsiniz.

Güncelleme 2:

Sorunun biraz daha kaynağına indiğimde çevirmen olarak otomatik peace seçildiğini gördüm, gariptir ki sitede de peace seçildiğinde sibnet linklerinde altyazı yok. Özetle uygulamada herhangi bir sorun yok fakat çevirmen seçeneği olmadığından alternatifsiz kalınıyor.

**Comment by KebabLord** [comment]
woah, elinde sonunda karşılaşacaktık bu problemle, geri dönüşün için çok teşekkürler.
İlk olarak sibnet türkanime'deki en yaygın ve en hızlı player, onu listeden çıkarmak gibi birşey mümkün değil. Youtube-dl sibnet'i indirirken jenerik fonksiyonlar kullanıyor, resmi olarak bi sibnet desteği yok. O yüzden nasıl olacak bilmiyorum ama bir şekilde altyazı olup olmadığını tespit etmeli ve o videoyu geçmeli ya da altyazıyı indirmeli. Fansub'u karalisteye alabiliriz, ama bu biraz kirli bir çözüm olurdu. Ne yapabiliriz bi bakayım.

**Comment by kemalsanli** [comment]
> woah, elinde sonunda karşılaşacaktık bu problemle, geri dönüşün için çok teşekkürler.
> Dediğin gibi, fark ettim ki videoda zaten altyazı yokmuş, fansub'un hatası, altyazıyı hardcore'layamamışlar. Yani bi bölümlük istisnai bir sorun. Ama fansub seçimi yapılamadığı için kullanıcıyı hapsediyor tek bir fansuba. "otomatik fansub seç" ayarı ve manuel olarak fansub seçebilme özelliği eklemek sorunu çözecek. TürkAnime fansub isimlerini bi çeşit hash code'u ile tutuyor o yüzden işimiz şimdiden sakat, yine de eklemeye çalışacağım.

Şöyle ki ilk sezonda 5-6 bölüm altyazısız şekilde gelmiş tek bölüm olsa issue açmazdım ama maalesef böyle olmuş, aynı söylediğiniz gibi fansub seçimi gelirse sorun düzeliyor en azından eski fork'ta böyle çalışıyor. Ama bence buradaki kilit nokta seçim şansı vermemesinin uploaderlar tarafından kötüye kullanılabilmesi olabilir. Eğer fansub seçeneğini ekleyebilirsen çok güzel olur. 

Bir miktar yorucu olabilir ama ellerine sağlık, gerçekten harika bir uygulama. Umarım kolay bir şekilde bu sorunu çözersin.

**Comment by KebabLord** [comment]
>Umarım kolay bir şekilde bu sorunu çözersin.

baya kararsızım aslında nasıl yapmam gerektiği konusunda. Mevcut haliyle bu uygulama fansub parametresini girmeden videoları talep ediyor, bu sayede tüm fansubların videosuna ulaşabiliyor. Belirli fansub üzerinden de playerlar talep edilebiliyor ama fazladan bir talep gerektirdiği için otomatik seçmeye kıyasla bir tık daha yavaş olur. Yine de url_getir() fonksiyonunu baştan yazmayı gerektirse de halledilir. Burda asıl soru işareti toplu video indirme işleminde fansub seçimini nasıl gerçekleştireceğimiz. Her video için tek tek fansub seçtirmek kulağa hoş gelmiyor, yığın video indirmeyi anlamsız kılıyor. Belki de eskisi gibi yalnızca bir video seçildiğinde fansub sormalı.  Gittikçe ilginçleşiyor.

>yandisk yerine yadisk yazıyor

uygulama videolara player butonlarını parse ederek ulaştığından player'ın gerçek isminden ziyade türkanimede butonlarda yazan ismi kullanmak zorunda. Bu haliyle bir sorun oluşturmuyor

**Comment by toprak** [comment]
Aga bence sadece tekli indirmelerde fansub seçtirme yap, diğer türlü bir anlamı kalmıyor.
