### ISSUE TITLE
Kaynak linkleri

### ISSUE THREAD

**Issue by byanonim** [KebabLord/turkanime-indirici#14]
Uygulama güzel çalışıyor. Elinize sağlık. İndirme işlemi yerine seçili kaynağın linkini txt olarak verme imkanı var mı? Mesela seçtiğimiz dizinin google drive linkleri?

**Comment by toprak** [comment]
Sorması ayıptır o zaman bu uygulamayı kullanmanın ne gereği var? Onun yerine direk fansublardan linkleri alabilirsiniz. Kaynak olarak zaten direk tanimede bulunan kaynakların video playerlarından söküp alıyor diye biliyorum.

**Comment by byanonim** [comment]
Google drive dan uygulama ile çekemiyorum. Bir çok kaynakta ham dosya yok. İşlenen videolar kalitesiz.

**Comment by KebabLord** [comment]
> Google drive dan uygulama ile çekemiyorum. Bir çok kaynakta ham dosya yok. İşlenen videolar kalitesiz.

bu uygulama da ham dosyaya ulaşmiyor. kabaca videolarin paylaşım url'lerini alıp indirme işlemini youtube-dl'e birakiyor. İdm ve eagleget türevleri yerine youtube-dl'e bakmanı tavsiye ederim.

**Comment by toprak** [comment]
Onu anlatmak istemiştim ben de ama.

**Comment by byanonim** [comment]
> > Google drive dan uygulama ile çekemiyorum. Bir çok kaynakta ham dosya yok. İşlenen videolar kalitesiz.
> 
> bu uygulama da ham dosyaya ulaşmiyor. kabaca videolarin paylaşım url'lerini alıp indirme işlemini youtube-dl'e birakiyor. İdm ve eagleget türevleri yerine youtube-dl'e bakmanı tavsiye ederim.

Python 3.6.7 kurulu. Bazı dizilerde aşağıdaki gibi hata alıyorum. 
https://prnt.sc/ym3u5o

**Comment by altanozlu** [comment]
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata
bu dökümana göre  `The following characters are not allowed: " \ / : | < > * ?` windows klasör isimlerinde : olamıyor, bu sembolleri klasör adlarından silerek ya da değiştirerek klasör oluşturulmalı. Şu an windowsda olmadığım için diğer arkadaşlara bırakıyorum meseleyi.

**Comment by KebabLord** [comment]
Düzeltildi 9cb352eaa2ac9ea461674acfe06d0fbd27229c71
