### ISSUE TITLE
Raspberry pi desteği

### ISSUE THREAD

**Issue by EnesCK-V1** [KebabLord/turkanime-indirici#16]
türkanime downloader için raspberry pi desteği getirebilir misin?

**Comment by KebabLord** [comment]
Aslında bu script zaten mevcut haliyle raspberry'de ve headless virtual machine'lerde çalişıyor. mpv ve youtube-dl kur, geckodriver'ın arm versiyonunu indir ve işlem tamam.

**Comment by KebabLord** [comment]
geckodriver-v0.32.0-linux-aarch64 sürümüyle pip aracılığıyla kurduğum bu scripti raspberry pi4 üstünde test ettim ve çalıştığını doğruladım. 
![image](https://user-images.githubusercontent.com/24779257/209449190-97ca255e-34e6-48d0-a4ac-ad66a604496b.png)
