### ISSUE TITLE
çok yavaş indiriyor

### ISSUE THREAD

**Issue by EnesCK-V1** [KebabLord/turkanime-indirici#17]
indirirken max 800kib/s hızları gördüm

**Comment by KebabLord** [comment]
Hangi playerdan indirirken bu hızla karşılaştın? Bu script destekledği alternatifleri kaliteliden yavaşa doğru sıralar. Sen bi bölüm açtığında mümkünse ilk olarak kaliteli player'dan video indirmeye çalişir. Eğer yavaş indirme hızı alıyorsan seçtiğin fansub hızlı bir player'a yüklememiş olabilir. Farklı fansublardan ayni bölümü indirmek sonucu değişmeli.

Yine de, bana iş göründü. Fabsublar arası otomatik en iyi player modu getirmeliyim. Yalnızca tek bir fansubun değil tüm fansubların playerlarini incelemeli.

**Comment by toprak** [comment]
Ben de anlayamadım, yanıt vermek için seni beklemiştim. Bende de bir sıkıntı yok.

**Comment by KebabLord** [comment]
> Ben de anlayamadım, yanıt vermek için seni beklemiştim. Bende de bir sıkıntı yok.

based

**Comment by EnesCK-V1** [comment]
sibnet ve mail.ru ile denedim ikiside 800kib/s den fazlasını vermedi sizin attığını ekran görüntüsündeki animeydi de adonisi seçerek indirdim 500kib/s ile indirmeye başladı

**Comment by toprak** [comment]
@EnesCK-V1 Görünüşe göre problem senin internette.

**Comment by EnesCK-V1** [comment]
internetim 9mb/s ile indirebiliyor

**Comment by EnesCK-V1** [comment]
iyi bir vpn ile denedim 8mb/s hıza çıktı ancak vpnin kota sınırı var o yüzden kullanımı mantıksız oluyor
