### ISSUE TITLE
fansub karışıklığı

### ISSUE THREAD

**Issue by EnesCK-V1** [KebabLord/turkanime-indirici#18]
her animede birden fazla fansub olsada fansub seçtirmiyor onun yerine sitedeki fansub seçim yerindeki en soldaki fansubı seçiyor bende 2 3 farklı fansubtan indirme oldu

**Comment by KebabLord** [comment]
![image](https://user-images.githubusercontent.com/24779257/117082006-c688bd00-ad49-11eb-9b6a-7b46bc9a2fb6.png)
Ayarlarda manuel fansub seçme ayarı var. Onu açacaksın arkadaşım. Bir de hiçbir ekran fotoğrafı, log, sistem bilgisi paylaşmadan nasıl yardımcı olmamı bekliyorsun, doğru dürüst issue aç.
