### ISSUE TITLE
Sibnet oynatılabilir video urlsi alma

### ISSUE THREAD

**Issue by mso45mso** [KebabLord/turkanime-indirici#22]
Merhaba android bir uygulamamda videoview içerisinde sibnetten alacağım url ile video oynatmak istiyorum ama sibnette videoyu başlatmadan oynatılabilir url ye ulaşamıyorum yardımcı olabilir misin?

**Comment by KebabLord** [comment]
players.py'deki iframe decryptleme yöntemini kullanarak sibnet urlsini elde ettikten sonra youtube-dl'nin --get-url parametresiyle videonun indirme linkini elde et, sonrasında ister videoyu oynat ister indir. Bu şekilde elde ettiğin video url'sini kullanmaya çalişirken 403 forbidden alabilirsin bu yüzden youtube-dl'in http headerlarına referer vs. eklemen gerek, istersen direk önceki sürümlere ait bu config dosyasını kullanabilirsin: https://github.com/KebabLord/turkanime-indirici/blob/396eedd8f04070fcf548696ddc3e7d3c003e8048/sibnet.conf
