### ISSUE TITLE
İndirme hızı neden 104Kib/s yi aşmıyor

### ISSUE THREAD

**Issue by Soulfly1984** [KebabLord/turkanime-indirici#24]
İndirme hızı neden 104Kib/s yi aşmıyor

_Originally posted by @Soulfly1984 in https://github.com/KebabLord/turkanime-indirici/discussions/23_

**Comment by KebabLord** [comment]
Seçmiş olduğun fansublar hızlı bir player'a video yüklememiş. Otomatik fansub ayarını aktifleştirdiğin takdirde fansub gözetmeksizin en hızlı playerı kullanılır.

**Comment by Soulfly1984** [comment]
> Seçmiş olduğun fansublar hızlı bir player'a video yüklememiş. Otomatik fansub ayarını aktifleştirdiğin takdirde fansub gözetmeksizin en hızlı playerı kullanılır.

Otomatik fansub açık olduğu halde böyle, ilk kurduğumda hızı 4Mb/s civarıydı.

**Comment by Soulfly1984** [comment]
İndirme hızı animeden animeye  değişiyor, farklı bi anime indirdiğimde gayet hızlı.
