### ISSUE TITLE
İndirme problemi

### ISSUE THREAD

**Issue by enescantas** [KebabLord/turkanime-indirici#25]
İndirme işleminde böyle bir hata ile karşılaşıyorum.
https://prnt.sc/19hx4rk

**Comment by KebabLord** [comment]
Bilgisayarındaki güvenlik yazılımından vs. kaynaklanıyor olabilir, exe'ye sağ tıklayıp özelliklerde "erişim engelini kaldır" tikini işaretlediğinden emin ol.

**Comment by KebabLord** [comment]
inaktiviteden ötürü kapatıl'd
