### ISSUE TITLE
Kalite Problemi

### ISSUE THREAD

**Issue by enescantas** [KebabLord/turkanime-indirici#26]
**Sorunu açıklayın**
Görüntü kalitesi problemli. Turkanime.tv üzerinden izlediğimde daha iyi görüntü oluyor.

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: Windows
 - Kullandığınız Sürüm: EXE

**Comment by KebabLord** [comment]
Manuel fansub seçme modunu aktifleştirip farklı fansublarda ve farklı bölümlerde denedin mi?

**Comment by KebabLord** [comment]
inaktiviteden ötürü kapatıl'd
