### ISSUE TITLE
Turkanime Domain Değişmesi

### ISSUE THREAD

**Issue by Soulfly1984** [KebabLord/turkanime-indirici#31]
Domain turkanime.co olarak değişmiş. Hiçbir şey çalışmıyor arama indirme vs.

**Comment by hakankarakis** [comment]
evet ben hatayi cözememistim demekki nedeni domain degismesi imis...

**Comment by KebabLord** [comment]
Şu commit ile a6289fe932d6b2b2dc993c36e622314efe6a6468 domain'i kabaca güncelledim ve yazılım source kod haliyle çalışıyor. Müsait olunca düzeltilmiş exe'leri yeniden derleyeceğim ve pip reposunu da düzelteceğim.

Şimdilik şuanki haliyle çalıştırmak isteyenler bilgisayarında python kuruluysa source kod'u kullanabilirler.

**Comment by KebabLord** [comment]
Bu arada bu postu görenler oylamaya katılabilir mi, uygulamanın hangi sürümünü kullanıyorsunuz? Tıklayarak oylayabilirsiniz.
[![](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/Statik%20versiyon%20(Turkanime.exe%20olarak%20servis%20edilen))](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/Statik%20versiyon%20(Turkanime.exe%20olarak%20servis%20edilen)/vote)
[![](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/Dinamik%20versiyon%20(Klas%C3%B6rl%C3%BC%20servis%20edilen))](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/Dinamik%20versiyon%20(Klas%C3%B6rl%C3%BC%20servis%20edilen)/vote)
[![](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/pip%20%C3%BCst%C3%BCnden%20%C3%A7al%C4%B1%C5%9Ft%C4%B1r%C4%B1yorum)](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/pip%20%C3%BCst%C3%BCnden%20%C3%A7al%C4%B1%C5%9Ft%C4%B1r%C4%B1yorum/vote)
[![](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/source%20kod%20%C3%BCst%C3%BCnden%20%C3%A7al%C4%B1%C5%9Ft%C4%B1r%C4%B1yorum)](https://api.gh-polls.com/poll/01FQN2A4QNT1X5DJPC1D68B8SV/source%20kod%20%C3%BCst%C3%BCnden%20%C3%A7al%C4%B1%C5%9Ft%C4%B1r%C4%B1yorum/vote)

**Comment by KebabLord** [comment]
yeni sürümleri (pip ve exe) hazırlayana dek bu issue açık kalsın

**Comment by KebabLord** [comment]
bugün itibariyle [yeni derlenmiş sürümü](https://github.com/KebabLord/turkanime-indirici/releases/tag/v7) yayınladığıma göre sorun çözüldü.
