### ISSUE TITLE
Edge desteği

### ISSUE THREAD

**Issue by Sparrow34tr** [KebabLord/turkanime-indirici#33]
uygulamayı firefox yerine Microsoft edge de çalıştırmak istiyorum bu yapılabilir mi?

**Comment by KebabLord** [comment]
Edge'in selenium desteği stabil mi yarım yamalak mı bilmiyorum ama bir webdriver'ı olduğunu biliyorum. Eğer kodu firefox yerine edge kullanacak şekilde güncellersen neden çalışmasın. [Şuradaki](https://github.com/KebabLord/turkanime-indirici/blob/master/turkanime_api/tools.py) "webdriver_hazırla" fonksiyonunu bir incele derim.

Benim anlamadığım neden edge?  Firefox'tan daha fazla ram kullanıyor ve dom renderlama hızı chrome'unkinden düşük.
Ayrıca scriptin bir webdriver kullanmasının tek sebebi cloudflare korumasını aşmak, sonrasında script ajax talepleri kullandığından farklı bir browser kullanmak performansı etkilememeli.

**Comment by KebabLord** [comment]
inaktiviteden dolayı kapatıldı, zaten cevabımın yeterli olduğunu düşünüyorum.
