### ISSUE TITLE
Uygulama terminalde çalışırken teminale tıklarsanız çökebiliyor.

### ISSUE THREAD

**Issue by kemalsanli** [KebabLord/turkanime-indirici#4]
Merhaba, 

Bu sorunu çözmek istedim ama önce size sorayım dedim bu durumdan haberiniz var mı diye, sorun bölüm seç dışındaki yerlerde mouse ile terminale tıkladığınzda uygulamanın çökmesi. Seçeneklerin illa üzerine tıklamanız gerekmiyor terminalin köşesine bile tıklasanız uygulama çöküyor.

https://user-images.githubusercontent.com/22424289/103811019-44270f80-506d-11eb-8a57-8fddad5e907f.mov

**Comment by toprak** [comment]
Denendi, Windows CMD'de de çöküyor. Haberi vardır belki.

**Comment by gokaybiz** [comment]
https://github.com/CITGuru/PyInquirer/issues/41
genel sorun...
