### ISSUE TITLE
İndirirken Hata

### ISSUE THREAD

**Issue by KaanAlper** [KebabLord/turkanime-indirici#40]
**Sorunu açıklayın**
Manual Fansub seçtikten sonra, indirme yaparken hata

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: Windows 10
 - Kullandığınız Sürüm: Kaynak Kod (Exe Güncellenmemiş Zaten)
 - Versiyon Güncel Kod
 - 
![image](https://user-images.githubusercontent.com/86665266/210244595-e1add6b0-14f1-441f-b2e0-207e307984f7.png)

**Comment by KaanAlper** [comment]
@KebabLord aga müsait bir zamanın da bakabilir misin acaba

**Comment by KebabLord** [comment]
artık o fansuba ait hiçbir player bulunamadığında aşağıdaki gibi hata verip devam edecek veya o bölümü atlayacak. Otomatik fansub ayarında her zaman çalışan bir player bulunduğu için hiçbir player bulunamadığında ne olacağına dair bir seçeneği görmezden gelmiştim hep. Dublaj gibi durumlar dışında her zaman otomatik fansubu kullanın derim.
![2023-01-02_22-18](https://user-images.githubusercontent.com/24779257/210271202-f93cf579-98c1-4bb7-9d15-25d441d5774e.png)

> Exe Güncellenmemiş Zaten

bunu nereden çıkardın?

**Comment by KaanAlper** [comment]
> artık o fansuba ait hiçbir player bulunamadığında aşağıdaki gibi hata verip devam edecek veya o bölümü atlayacak. Otomatik fansub ayarında her zaman çalışan bir player bulunduğu için hiçbir player bulunamadığında ne olacağına dair bir seçeneği görmezden gelmiştim hep. Dublaj gibi durumlar dışında her zaman otomatik fansubu kullanın derim. ![2023-01-02_22-18](https://user-images.githubusercontent.com/24779257/210271202-f93cf579-98c1-4bb7-9d15-25d441d5774e.png)
> 
> > Exe Güncellenmemiş Zaten
> 
> bunu nereden çıkardın?
Şey ehe xD her baktığımda eski versiyondu güncellenmiş xd, bir de şey soracağım çoklu video indirmelerinde fansub sormuyor. alfabeden seçiyor. orda varsayılan ayarlama diye bir seçenek olsa o fansub olmadğında böyle bir şey olsa daha mantıklı bence, tekrardan eline sağlık bro

**Comment by KebabLord** [comment]
tamamdır, sıradaki release'e varsayılan fansub'u hatırlamaya ilişkin bir sistem ekleyeceğim.
>tekrardan eline sağlık

senin için kullanışlıysa ne mutlu bana

**Comment by KaanAlper** [comment]
> tamamdır, sıradaki release'e varsayılan fansub'u hatırlamaya ilişkin bir sistem ekleyeceğim.
> 
> > tekrardan eline sağlık
> 
> senin için kullanışlıysa ne mutlu bana


aga birde fazla oldum biliyom ama, one piece gibi bir anime izlerken 1000. bölümden 1001 e geçmek biraz zor oluyor baştan yukarı kadar çıkmak gerekiyor, sıradaki release de otomatik sonraki bölüme geçme veya o tarz bişe ekleyebilir misin?

**Comment by KebabLord** [comment]
o özelliği zaten ekledim ki son release'de. Güncellemedin mi hala? Kaldı ki açtığın discussion başlığında da belirttim eklediğimi: #35
video:
https://user-images.githubusercontent.com/24779257/209420172-630e3e8d-a592-42e6-86ba-bd2b57a6408d.webm

ayarlarda izlenme ikonu diye geçiyor bu özellik.
