### ISSUE TITLE
donghuatr

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#46]
Merhabalar, başlıktaki sitede aslında aynı mantıkta çalışıyor.
Belki daha kolay bile olabilir.
https://prnt.sc/VDkAtjKss7A- Ben bile böyle birşey buldum. 
Base64decode ettiğimde ise  https://prnt.sc/z30hTrNhv7d1 bu şekilde birşey çıktı.
beautifier.io dan okunabilir hale getirdiğimde ise sonuç: https://prnt.sc/ePgsWBol9icS
Bunu da ekleseniz çok memnun olurum.
Başlıktaki site turkanime den içerik olarak belki az olabilir ama tarz olarak çok çok farklı ve daha düzenlidir.
Saygılarımla

**Comment by KebabLord** [comment]
siteyi inceledim, anime veritabanı konusunda limitli olsa da yaklaşık 200 çin animasyonu barındırıyor ve bir potansiyeli var. Ancak API tamamen farklı ve bu mevcut repo ile pek bir alakası yok, bir kaç hamlede birleştirilebilecek birşey değil. Kaldı ki zaten bu repo'yu maintain etmekte yeterince tembel ve isteksiz olduğumu düşündüğümde üstüne bir de bu siteyi ekleyip aynı anda 2 site üstündeki değişiklikleri entegre edip durmak kesinlikle efor harcayamayacağım bir konu. 

Şüphesiz ki donghua üstüne bir anime indirici veya api yaratılacaksa, bu repo'dan tamamen bağımsız yeni bir repo ve script oluşturulması gerekiyor.
