### ISSUE TITLE
Download Hızı

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#47]
**Sorunu açıklayın**
https://prnt.sc/b-hOscW5GC7Z
Aynı Anime, Aynı Sibnet URLsi, idm ile 12mbits indirirken program ile 200 küsür kb hızda indiriyorum. Neden bu kadar farklı acaba ?
Teşekkürler.

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: [Win10 x64]
 - Kullandığınız Sürüm: [EXE 7.0.4]
 - Versiyon [https://github.com/KebabLord/turkanime-indirici/releases/tag/v7.0.4]

**Comment by KebabLord** [comment]
idm'de indirdiğin url ile turkanime-indirici'dekinin aynı url olduğundan emin misin? Dosyalardan birisi 257 mb iken diğeri 244 mb. Turkanime-indirici farklı bir player üstünden indirmeye çalışıyor olabilir.

**Comment by Prohibitive** [comment]
Evet eminim.

**Comment by KebabLord** [comment]
ilginç, durum çözüldüğüne göre issue'yi kapatıyorum.
