### ISSUE TITLE
Sayfalama

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#48]
**Sorunu açıklayın**
https://www.turkanime.co/anime/ashita-no-joe
Toplamda 79 bölüm ve ekrana sığmadığı için sığan kadar gözüküyor (60 bölüm). Sanırım sayfalama ile alakalı bir durum.
https://prnt.sc/tJ33nHRudERO

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: [örn. Windows, Linux]
 - Kullandığınız Sürüm: [örn. EXE sürüm, kaynak kod]
 - Versiyon [örn. v5.3.1,v6,güncel github kodu]

**Comment by KebabLord** [comment]
Kendi kişisel bilgisayarımda test ettiğimde sorunsuz çalıştığını görüyorum
![2023-03-15_05-28](https://user-images.githubusercontent.com/24779257/225189100-98363275-68f2-4d2d-be86-3d1ef93418bf.png)

Issue açarken gerekli bilgileri doldurmadığın için ilaveten tekrar soruyorum, hangi sürümü kullanıyorsun EXE sürümü mü, pip sürümünü mü yoksa kaynak koddaki versiyonu mu? Windows sürümün nedir?

>ekrana sığmadığı için
script default'da cmd üstünden çalışıyor, powershell üstünden çalıştırdığında aynı sorunu gözlemliyor musun? Diğer serilerde sorun devam ediyor mu?

**Comment by KebabLord** [comment]
inaktiviteden dolayı şimdilik kapatıyorum
