### ISSUE TITLE
Bölüm seçiminde bölümler eksik geliyor.

### ISSUE THREAD

**Issue by kemalsanli** [KebabLord/turkanime-indirici#5]
Merhabalar,

Bu sorunun nedenini araştırıyorum bulabilirsem çözeceğim, görselde görebileceğiniz gibi 16.bölümden sonrası yok. Naruto çok fazla bölüme sahip olduğu için belki doğru bir örnek olmayabilir fakat persona 4 animesinde de 20 bölüm olmasına rağmen aynı sorun mevcut.

![Ekran Resmi 2021-01-06 22 25 27](https://user-images.githubusercontent.com/22424289/103811527-155d6900-506e-11eb-8a2d-81582fad9289.png)

Emeğinize teşekkürler.

**Comment by toprak** [comment]
Rainbow: Nisha Rokubou no Shichinin, 26 bölümlük anime 16. bölümünden sonra bende de bölümler gözükmedi. One Piece'de de aynı. 5-toubun no Hanayome 12 bölüm olduğu için hepsi gözüktü.

**Comment by altanozlu** [comment]
Acaba türkanime’nin sitesinde bir değişiklik mi oldu

**Comment by kemalsanli** [comment]
> Acaba türkanime’nin sitesinde bir değişiklik mi oldu

Büyük ihtimal öyledir diye düşünüyorum, aslında workaround olarak seçilen iki indis arasındaki bölümler alınabilir, veya youtube-dl usulü url ile de çalışabilir.

**Comment by gokaybiz** [comment]
Turkanimede bir degisiklik yoktu fakat search_api'de duzgun calisiyor olmasina ragmen proje icersinde bos eleman donduruyordu, bir takim degisiklikler neticesinde sorun cozuldu.
https://github.com/KebabLord/turkanime-indirici/commit/ccf5b5d18b485e198c0ac9b6708a787e37e2d223
