### ISSUE TITLE
Otomatik download?

### ISSUE THREAD

**Issue by rifatozkancomtr** [KebabLord/turkanime-indirici#59]
Yeni siteler ve otomatik download ekleyebilir misin?
Örneğin tüm sitedeki animeleri en yüksek kalitede otomatik olarak download yapacak yeni bölüm eklenince eklenen bölümü indirecek.

:) ücreti mukabilinde ne kadar olur böyle bir özellik?

**Comment by KebabLord** [comment]
iletişim: [juchi.zip/gpg](https://juchi.zip/gpg.html)
