### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by dogan125** [KebabLord/turkanime-indirici#60]
Programın güncel halini kullanıyorum youtube-dl yüklenmiyor program kendi kendini kapatıyor. Manuel kurulum için klavuz.html nerde bulamadım.
![asdasdfasfasfa](https://github.com/KebabLord/turkanime-indirici/assets/141375664/2abfd635-6113-4505-b02c-a6a9bb88e2b8)

**Comment by hakankarakis** [comment]
Hocam bende de aynisi oluyordu bende youtube dl yi ve diger parcayi googleden aratip indirdim sonra turkanimeindirici ile ayni klasöre koydum calisti

**Comment by hakankarakis** [comment]
https://www.computerbild.de/download/YouTube-DL-30148257.html


https://github.com/mozilla/geckodriver/releases
