### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#62]
Exe olarak güncellini indirmeme rağmen aşağıdaki hatayı alıyorum. Sadece aşağıdaki animede değil hepsinde aynı hatayı alıyorum. Download yaparken kapattım ondan sonra oldu. Ne yapmam gerekiyor?

`? Animeyi yazın Free! Eternal Summer: Kindan no All Hard!
 Traceback (most recent call last):
  File "turkanime.py", line 81, in <module>
  File "turkanime_api\anime.py", line 65, in mark_bolumler
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[5292] Failed to execute script 'turkanime' due to unhandled exception!
Program kapatılıyor..
C:\Users\Administrator\TurkAnimu>`

 - İşletim Sistemi: Windows
 - Kullandığınız Sürüm: TürkAnimu.exe 
 - Versiyon V7.0.4
@KebabLord 
Rica etsem yardımcı olabilir misiniz?

**Comment by KebabLord** [comment]
Öncelikle geri bildirimde bulunduğun için teşekkür ederim.
Görünüşe bakılırsa `C:\Users\Administrator\TurkAnimu\gecmis.json` dosyası bozulmuş gibi görünüyor, buraya atar mısın içeriğini? Buraya attıktan sonra dosyayı TurkAnimu klasöründen silersen ve scripti yeniden başlatırsan sorun çözülecektir.

Bir iki hafta içinde V8'in exe versiyonunu da yayınlayacağım, onu kullanmak istersen [source kod'dan python ile çalıştırabilirsin](https://github.com/KebabLord/turkanime-indirici/wiki/Source-Kod'dan-Script'i-%C3%87al%C4%B1%C5%9Ft%C4%B1rma) aklında bulunsun.

**Comment by Prohibitive** [comment]
> Öncelikle geri bildirimde bulunduğun için teşekkür ederim. Görünüşe bakılırsa `C:\Users\Administrator\TurkAnimu\gecmis.json` dosyası bozulmuş gibi görünüyor, buraya atar mısın içeriğini? Buraya attıktan sonra dosyayı TurkAnimu klasöründen silersen ve scripti yeniden başlatırsan sorun çözülecektir.
> 
> Bir iki hafta içinde V8'in exe versiyonunu da yayınlayacağım, onu kullanmak istersen [source kod'dan python ile çalıştırabilirsin](https://github.com/KebabLord/turkanime-indirici/wiki/Source-Kod'dan-Script'i-%C3%87al%C4%B1%C5%9Ft%C4%B1rma) aklında bulunsun.

Cevabın için tşk ederim.
[gecmis - Kopya.json](https://github.com/KebabLord/turkanime-indirici/files/13950763/gecmis.-.Kopya.json)
Ekte gönderiyorum.
v8 hasretle bekliyor olacağım. 
Saygılarımla

**Comment by KebabLord** [comment]
geri dönüşün için çok teşekkür ederim. Görünüşe bakılırsa program gecmis.json'a verileri kaydederken resimde belirttiğim şu son 3 satırı ekleyemeden kapanmış.
![resim](https://github.com/KebabLord/turkanime-indirici/assets/24779257/8501dac8-5bec-41bc-872e-4b08014bdbb1)

Bunun gibi durumların yaşanmaması için şu şekilde ufak bi kod yazı vereceğim exe'yi yayınlamadan önce:
```
1. gecmis.json'u temp'e kopyala
2. kopyada gerekli değişiklikleri gerçekleştir
3. başarıyla gerçekleşirse orjinal gecmis.json'un üstüne taşı
```

Senin gecmis.json'u da o 3 satırı manuel olarak ekleyerek düzelttim kullanmak istersen: [gecmis.-.Kopya.json](https://github.com/KebabLord/turkanime-indirici/files/13982375/gecmis.-.Kopya.json)

**Comment by Prohibitive** [comment]
@KebabLord Çok teşekkür ederim. Saygılarımla
