### ISSUE TITLE
V8 İndirme Mantığı

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#64]
Merhabalar,
Download mantığını anlamak için birkaç sorum olacaktı.
Ayarlar:
![image](https://github.com/KebabLord/turkanime-indirici/assets/22181509/6a250763-6761-435e-8ae8-df0d269a130b)

Örnek URL: https://www.turkanime.co/video/bleach-sennen-kessen-hen-1-bolum
Sanırım ilk önce Fansubları tarıyor.
![image](https://github.com/KebabLord/turkanime-indirici/assets/22181509/33ef7640-add8-4489-8bb5-646b56bf8cce)
Manuel Fansub  Seç Kapalı olduğu için ilk Fansubu alıyor (AnimeWho)
Animewho u seçip Nerelere upload edildiğini kontol ediyor.
![image](https://github.com/KebabLord/turkanime-indirici/assets/22181509/d7448640-006b-4b4d-9fba-161d7b350c35)
Sonrasında ise Programdaki öncelikli download sırasına göre (Drive,Mail vs vs) download ediyor?
Veya
Animewho yu seçtikten sonra download sırası göre (Drive,Mail vs vs) hepsini tarıyor ve 1080p olanları ayrıştırıp tekrar download sırasına göre (Drive,Mail vs vs) indirmeye başlıyor?
Doğru mudur?
@KebabLord

**Comment by Prohibitive** [comment]
@KebabLord mantık harikasıymış :D
turkanimenin sahibi görmesin bunu silelim lütfen :DD

**Comment by KebabLord** [comment]
2019'dan beri Schneizel üstadla yarış halindeyiz zaten, endpointleri güncelliyor, domainleri güncelliyor, kötüye kullanmayalım diye iframe'leri şifreliyor, javascript kodunu obfuscate eyliyor vs. O da bıktı sanırım artık :D

**Comment by Prohibitive** [comment]
👍 üstad bu ok.ru ortalama ne kadar sürede yayınlanır acaba ?

**Comment by KebabLord** [comment]
@Prohibitive şuan düzeltilmiş halini yayınladım dost.
Aria2c'yi de entegre ettim, ayarlardan açıp onu da deneyebilirsin.

Güncel exe:
https://github.com/KebabLord/turkanime-indirici/releases/tag/V8.2.1

geri bildirimlerini bekliyor olacağım.

**Comment by KebabLord** [comment]
bu issue yanıtlandığına göre kapayabilirim, script'e ilişkin bir problem gözlemlersen yeni bir issue açmaktan çekinme
