### ISSUE TITLE
Sıralama Arızası

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#67]
**Sorunu açıklayın**
Ayarlarım:
![image](https://github.com/KebabLord/turkanime-indirici/assets/22181509/766d6cec-3657-4700-be6c-298f63d6418f)
bu şekilde olmasına rağmen ve çalışan OK.ru olmasına rağmen MAIL den indiriyor.
![image](https://github.com/KebabLord/turkanime-indirici/assets/22181509/0dee25aa-db4c-45d5-967f-b6745455b953)
URL: 
https://www.turkanime.co/video/uta-no-prince-sama-2-1-bolum

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: Windows 10
 - Kullandığınız Sürüm: Kaynak Kod
 - Versiyon v8.2.2

**Comment by KebabLord** [comment]
source kodda değişiklikler yaptıktan sonra script'i şu şekilde çalıştırdığına emin misin?
```
py -m turkanime_api.cli
```

aksi halde farklı bir biçimde çalıştırıyorsan muhtemelen değişiklik yaptığın sürümü değil halihazırda kurulu olan sürümü kullanıyor olabilirsin

**Comment by Prohibitive** [comment]
evet dostum lakin sonradan farkettim deneysel aria dan indirme kapalı imiş 🗡️ 
Açık yaptım ve düzeldi 🗡️ 
Kusura bakma lütfen
