### ISSUE TITLE
Failed to execute script "compiled" due to unhandled exception!

### ISSUE THREAD

**Issue by EnesCK-V1** [KebabLord/turkanime-indirici#70]
**Sorunu açıklayın**
Daha önce indirme yaptım ve ekstra kurcalamamış olmama rağmen ikinci kez çalıştırdığımda böyle bir hata aldım
![image](https://github.com/KebabLord/turkanime-indirici/assets/74046770/c7002bf1-5db6-4761-a36d-dfc1e6f76431)

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: Windows 10
 - Kullandığınız Sürüm: exe sürümü
 - Versiyon V8.2.2

**Comment by KebabLord** [comment]
görünüşe bakılırsa gecmis.json'a yeni entry girilirken bozulmuş, bu daha önce de rapor edilmiş bir hata: #68
çözmek için şu commit'i yapmıştım b4fd8f9ed1fcc2b6be7a1d1b50c341c05f2f8d77 ancak işe yaramamıştı. Sıradaki release'de düzelteceğim.

Şimdilik anime izleme ve indirme geçmişini silecek olsa da `gecmis.json`'u silmek uygulamanın tekrar düzgünce çalışmasını sağlayacaktır.

EXE sürümü kullananlar için windows'ta gecmis.json'un konumu:
C:\Users\kullanici_adin\TurkAnimu\gecmis.json dizininde

Silmeden önce buraya içeriğini yüklersen fena olmaz.
Hatayı rapor ettiğin için çok teşekkür ederim.

**Comment by EnesCK-V1** [comment]
Yardımın için teşekkür ederim, gecmis.json dosyasını ekledim ^^

[gecmis.json](https://github.com/KebabLord/turkanime-indirici/files/14891502/gecmis.json)
