### ISSUE TITLE
Başaltma Hatası

### ISSUE THREAD

**Issue by byanonim** [KebabLord/turkanime-indirici#8]
Python 3.6.7 sürümünde uygulama başlatılamıyor. Aşağıdaki hatayı alıyorum.
https://prnt.sc/wrypbf

**Comment by KebabLord** [comment]
python program dizininde geckodriver.exe'yi bulamıyor. Eğer indirip yerleştirmediysen lütfen klavuzdaki kurulum talimatlarını izle:
https://j0n.k4w411.net/turkanime-indirici/klavuz.html

**Comment by KebabLord** [comment]
python program dizininde geckodriver.exe'yi bulamıyor. Eğer indirip yerleştirmediysen lütfen klavuzdaki kurulum talimatlarını izle:
https://kebablord.github.io/turkanime-indirici/klavuz.html

**Comment by byanonim** [comment]
Programı çalıştırdım ama bu seferde videolar inmiyor. Sadece google ve ok.ru kaynaklarını ayarladım ancak hepsi de aktif olsa fotoğraftaki hatayı alıyorum.

https://prnt.sc/wto7sz

**Comment by KebabLord** [comment]
Haklısın, programı linux üstünde geliştirdim ancak hiç windows üstünde test yapmadım doğru dürüst, sayende farkettim eksikleri.
- Satır temizleme fonksiyonu windowsta çalışmıyor, \[2K\[1G şeklinde kalıyor
- youtube-dl tırnak işaretleriyle problem yaşıyor
- kullanım talimatları yeterli değil
- Program açılışta geckodriver'ın mpv'nin ve youtube-dl'in kurulu olduğunu kontrol etmeli

Bir kaç saat içinde eksiklikleri giderip windowsta sorunsuz çalıştığından emin olduktan sonra programı derleyip yeni bir indirilebilir release yayınlayacağım. Teşekkürler.

**Comment by KebabLord** [comment]
Son commitle birlikte Windows 7'de test ettiğimde sorun çözülmüş gibi duruyor.
